### ISSUE TITLE
Branching Terminology & Methodology - Please Confirm?

### ISSUE THREAD

**Issue by lokesh75way** [thecodeclimber/bluejay-frontend#16]
@thecodeclimber Now I have deleted the unusual branches and only kept the `feature/bigcommerce` branch. Starting from here we will create new feature branches from `feature/bigcommerce` branch, for ex : for home page Kirti have created new branch `feature/bigcommerce/home` from `feature/bigcommerce` branch. And once the feature is completed then we will merge it to `feature/bigcommerce` branch. 

We can always use `feature/bigcommerce` branch to deploy into `main` branch. So that we don't need to be depend on you to deploy the feature branches every day because most of the times we have dependent features in the previous branches which we need in the current one. 

Let me know if you agree on this or else advise?
Thanks

**Comment by thecodeclimber** [comment]
@lokesh75way -- let's use the method outlined in issue #18
