### ISSUE TITLE
Need Vercel Account Access on URGENT BASIS

### ISSUE THREAD

**Issue by lokesh75way** [thecodeclimber/bluejay-frontend#17]
@thecodeclimber In order to see the failed test cases in the build, I need access to the VERCEL account because currently I am not sure why the build is getting failed. So please provide me access to the VERCEL account so that I can investigate the errors and fix it tomorrow. Thanks

**Comment by thecodeclimber** [comment]
I will get working on this -- I need to set you up as a team member.  I also want to move this repository over to the github bluejay organization (and sync up vercel to that repository).  I will try and work on this tomorrow.

**Comment by thecodeclimber** [comment]
This issue is dependent upon the successful implementation of issue #29

**Comment by thecodeclimber** [comment]
I am closing this issue -- tasks moved over to issue #29
