### ISSUE TITLE
Create Git Workflow

### ISSUE THREAD

**Issue by thecodeclimber** [thecodeclimber/bluejay-frontend#18]
I want to create some structure to our branches and issues.

# Overall Structure

Here is a list of the different type of branches:

* `main` -- for production
* `develop` -- for development
* `release` -- for stable release versions
* `hotfix` -- to patch a production release
* `feature` -- for new features
* `issue` -- for branches related to issues

This video gives a nice summary of how this works: https://www.youtube.com/watch?v=1SXpE08hvGs

Let me just add the following about `feature` and `issue` branches:

## Feature

Feature branches will be new features that we introduce.  They will have the following naming structure

* feature/{feature name}

Example: `feature/cart-design`

## Issue Branches

Issue branches will be branches that are created in response to issues created in the Issues section of github.  They will have the following naming structure:

* issue/#{issue number}--{issue name}

Example: `issue/#11--search-solution`

Note, btw, the double dash between the number and the name.  I.e., this is correct: 

* `#11--search-solution`.  

This is NOT correct: `

* `#11-search-solution`

# Tasks

* Create `develop` branch
* Rename current branches according to the above structure
* Use this system for future branches

**Comment by lokesh75way** [comment]
Ok I will start renaming tomorrow, Thanks

**Comment by lokesh75way** [comment]
@thecodeclimber 
Updated the below branches name
- feature/bigcommerce —> develop
- feature/bigcommerce-home —> issue/#20--code-home-page-figma-design
- feature/bigcommerce-cart —> issue/#21--code-cart-figma-design

Workflow:
Now `develop` branch is created from `main` branch and rest branches are created from develop

-  `develop` branch's PR will create for `main` branch
-  `issue/#20--code-home-page-figma-design` branch's PR will create for `develop` branch
-  `issue/#21--code-cart-figma-design` branch's PR will create for `develop` branch

Please let me know if need anything from my side.
Thanks
