### ISSUE TITLE
Using labels

### ISSUE THREAD

**Issue by thecodeclimber** [thecodeclimber/bluejay-frontend#19]
Hi there,

I would like to start using labels inside of github issues as follows:

# Three types of issues:

* work
* bugs
* questions & answers

## Work Labels

* Not Started
* In Progress
* Waiting
* Review
* Done

### Explanation

* `Not Started` -- all new issues start off with the `Not Started` label.
* `In Progress` -- once we begin working on an issue we change the label from `Not Started` to `In Progress`
* `Waiting` -- if we need someone else's input or advice we switch the label to `Waiting`
* `Review` -- If we have finished an issue and need approval we switch the label to `Review`
* `Done` -- when an issue has been reviewed and is finished we switch the label to `Done`

**Note:** Once an issue is labeled as `Done` we can close the issue.

## Bug Lables

* Bug
* Fixed

### Explanation

* `Bug` -- for identifying bugs that need to be addressed.  We can then create a new issue or multiple new issues once we have analyzed the bug.  
* `Fixed` -- when a bug is fixed, we change it's label to `Fixed`

**Note:** Once an issue is labeled as `Fixed` we can close the issue.

## Question & Answer Labels

* Question
* Answer
* Satisifed
* Not Satisfied

### Explanation

* `Question` -- for questions and clarifications.  All questions start off with the `Question` label.  
* `Answer` -- when a question is answered, the label is switched to `Answer`.  
* `Not Satisfied` -- if we are not happy with an answer we switch the label to `Not Satisfied` (offering an explanation of why we are not satisfied).  
* `Satisified` -- if we are happy with the answer we switch the label to `Satisfied`.  

**Note:** Once an issue is labeled as `Satisfied` we can close the issue.

---

Please let me know if you would like to make any changes to this system.  Thanks.

**Comment by thecodeclimber** [comment]
Note, I renamed `Not Satisfied` to `More Explanation` so as not to confuse `Not Satsified` with `Not Started`.

**Comment by thecodeclimber** [comment]
@lokesh75way -- please take a look at the above issue.  Thanks.

**Comment by thecodeclimber** [comment]
@lokesh75way  -- please note, sometimes when we change a label we will also need to reassign the issue.  For example, when changing a label to `Review` we will have to also assign the issue to whoever it is that does the review.

**Comment by lokesh75way** [comment]
Noted
