### ISSUE TITLE
Code Cart Figma Design

### ISSUE THREAD

**Issue by thecodeclimber** [thecodeclimber/bluejay-frontend#21]
# Figma Link

Cart: https://www.figma.com/file/YQSaBNNhDfFjEPRQbGObeh/?node-id=4277%3A14373

**Comment by lokesh75way** [comment]
@thecodeclimber 
- created drawer element 
- created cart added page

**Comment by thecodeclimber** [comment]
Hi there,

I am not sure what you mean by “drawer element” or “cart added page”.

Can you please give me links in the code AND on the finished site where I can see these?

Thanks

**Comment by lokesh75way** [comment]
@thecodeclimber 
Vercel link of cart page : https://bluejay-frontend-amwc6mwla.vercel.app/cart

PR link:  https://github.com/thecodeclimber/bluejay-frontend/pull/33

Please click on the top right side cart button to open drawer.
Drawer element commit code link: https://github.com/thecodeclimber/bluejay-frontend/pull/33/commits/1db6952bad7cbc83ac185ae38e314dc5d21aac8d

**Comment by thecodeclimber** [comment]
@lokesh75way 

Nice.  Can we also add the possibility to close the drawer by using the Esc key?

**Comment by lokesh75way** [comment]
Sure I will add esc key functionality
