### ISSUE TITLE
Fix next/Image error

### ISSUE THREAD

**Issue by thecodeclimber** [thecodeclimber/bluejay-frontend#30]
**SEE BELOW FOR CODE SNIPPET & SCREEN SHOT OF THE ERROR**

--

My guess is that this error is caused by a typo -- namely, that the code should be: `next/image` not `next/Image`.

I.e., that the `i` in `image` should be lowercase (right now it is uppercase).  Please try making that change and I'll let you know if it fixes the problem.

--

If it does NOT fix the problem, then we will have to wait for the successful completion of issue #29 

### Code Snippet
```
15:25:47.462 | Failed to compile.
-- | --
15:25:47.462 | ModuleNotFoundError: Module not found: Error: Can't resolve 'next/Image' in '/vercel/workpath0/components/product/productDetail/specification/imageGallery'
15:25:47.463 | > Build error occurred
15:25:47.464 | Error: > Build failed because of webpack errors
15:25:47.464 | at build (/vercel/workpath0/node_modules/next/dist/build/index.js:15:918)
15:25:47.464 | at runMicrotasks (<anonymous>)
15:25:47.464 | at processTicksAndRejections (internal/process/task_queues.js:97:5)
15:25:47.492 | error Command failed with exit code 1.
15:25:47.493 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
15:25:47.510 | Error: Command "yarn run build" exited with 1
```

### Screenshot
![image](https://user-images.githubusercontent.com/65869221/103048822-87c34900-4598-11eb-9c5d-d91658a4df51.png)

**Comment by lokesh75way** [comment]
Already fixed in develop
