### ISSUE TITLE
Customer Signup Fields

### ISSUE THREAD

**Issue by lokesh75way** [thecodeclimber/bluejay-frontend#7]
Now since we are using the BigCommerce api with our react/next app. But in the customer signup there are some mandatory parameters asked by bigpost like (address, phone etc) which are in present in our register design? So what should we do in that case?

Reference URL:
https://developer.bigcommerce.com/api-reference/store-management/customers-v3/customers/customerspost

Should I create those required field in our signup form?

**Comment by thecodeclimber** [comment]
If we have to create those fields – then yes, please create them.

Also, in terms of accounts – we are thinking of a two or three tiered account structure.

Tier number one:  Company
Tier number two:  Salesman
Tier number three:  Customer


A salesman belongs to a company.  A customer can either purchase on their own or via a salesmen.  In practice, though, we’ll probably have to do this through groups (and I don’t think that groups allow for hierarchical structures).  I’ll give specifics later.  For now, let’s just create the company accounts and we’ll worry about the groups later on.
