### ISSUE TITLE
Code the Rest of the Figma Designs

### ISSUE THREAD

**Issue by thecodeclimber** [thecodeclimber/bluejay-frontend#9]
[from email that i just sent you - so that we can track this in github]

...we also need to code the other elements of the figma design.  Here is the order in which I would like to tackle the designs:

•	Home Page:  https://www.figma.com/file/YQSaBNNhDfFjEPRQbGObeh/?node-id=4277%3A14369
•	Cart: https://www.figma.com/file/YQSaBNNhDfFjEPRQbGObeh/?node-id=4277%3A14373
•	Order:  https://www.figma.com/file/YQSaBNNhDfFjEPRQbGObeh/?node-id=4277%3A14377
•	Category Pages: https://www.figma.com/file/YQSaBNNhDfFjEPRQbGObeh/?node-id=4277%3A14372
•	Product Pages: https://www.figma.com/file/YQSaBNNhDfFjEPRQbGObeh/?node-id=4277%3A14371
•	Contact Page: https://www.figma.com/file/YQSaBNNhDfFjEPRQbGObeh/?node-id=4277%3A14375
•	About Page: https://www.figma.com/file/YQSaBNNhDfFjEPRQbGObeh/?node-id=4277%3A14374

**Comment by lokesh75way** [comment]
Current State : 
• Home Page: Kirti is currently working on the UI
• Cart: This is pending, will start on it soon
• Order: UI is already done
• Category Pages: UI is done for 3 pages, 1 is pending
• Product Pages: Kirti worked on it. UI is done for 1 page, rest of the pages are pending
• Contact Page: UI is already done
• About Page: UI is already done

**Comment by thecodeclimber** [comment]
Thanks for the update. 

I am going to separate out each of these sections into their own issue so that we can keep better track of them.

**Comment by thecodeclimber** [comment]
@lokesh75way I have created different issues for each of the above sections.  Please take a look at them.

Also -- please create a separate branch for each of these new issues in accordance with the branching system that I discussed in issue #18 

Thanks.

**Comment by thecodeclimber** [comment]
@lokesh75way -- also, please let me know when you have created those new branches.  Thanks.
